graph TD
  subgraph Presentation_Layer
    ServiceAPI
  end

  subgraph Business_Logic_Layer
    HBNBFacade
    User
    Place
    Review
    Amenity
  end

  subgraph Persistence_Layer
    Repositories
  end

  ServiceAPI --> HBNBFacade
  HBNBFacade --> User
  HBNBFacade --> Place
  HBNBFacade --> Review
  HBNBFacade --> Amenity
  HBNBFacade --> Repositories

  Note1[/"HBNBFacade represents the Facade Pattern,\nsimplifying the interaction between layers."/]
  HBNBFacade -.-> Note1
